import pysrt

SRT_PATH = "data/final_american_beef_vlog.zh.srt"

translations = {
    "贵不贵啊": "Is it expensive?",
    "不贵不贵": "It's not expensive at all.",
    "这么好的肉": "Such good meat.",
    "哇 这可以": "Wow, this looks great.",
    "很漂亮": "It looks beautiful.",
    "这个肉怎么样": "How is this meat?",
    "十八块这么靓": "Only 18 yuan, so fresh!",
    "老板说每个肉都很靓": "The boss says every piece of meat is top quality.",
    "广东人做生意不骗人的。": "Guangdong people are honest in business.",
    "今天在广东佛山的肉场": "Today we are at a beef factory in Foshan, Guangdong.",
    "买牛肉吃到爽": "Buying beef and eating to our hearts' content.",
    "看看仨人要花多少": "Let's see how much it costs for three people.",
    "这里是佛山的高明": "This is Gaoming in Foshan.",
    "这叫牛街": "It's called Cattle Street.",
    "这旁边就是肉场": "Right next to it is the beef factory.",
    "靓仔，买牛肉了": "Hey handsome, buying beef now.",
    "吊龙多少钱啊": "How much is the Chuck Flap?",
    "50块钱": "50 yuan.",
    "水牛 黄牛都有": "We have both water buffalo and local cattle.",
    "哪个好吃啊": "Which one is tastier?",
    "我们本地人就是水牛多": "We locals mostly eat water buffalo.",
    "我们刚来，先逛一逛": "We just came here, taking a look around first.",
    "你们本地吃黄牛多还是水牛多？": "Do locals here eat more local cattle or water buffalo?",
    "肯定是黄牛好吃咯": "Local cattle is definitely tastier.",
    "水牛骚味比较重": "Water buffalo has a slightly stronger gamey taste.",
    "比较柴，有点老": "The meat is leaner and a bit tough.",
    "这个是安格斯牛肉": "This is Angus beef.",
    "进口的": "Imported.",
    "是国产的": "It's domestic.",
    "内蒙古运回来的": "Shipped all the way from Inner Mongolia.",
    "这个大吊龙80块": "This large Chuck Flap is 80 yuan.",
    "这有点贵哦": "That's a bit expensive.",
    "安格斯不讲价": "No bargaining for Angus beef.",
    "哦": "Oh.",
    "全都是有花的": "They all have good marbling.",
    "哦 行行行": "Oh, okay, okay.",
    "给我切一点": "Cut a little bit for me.",
    "半斤左右了": "Make it around half a catty (250g).",
    "46啊": "46 yuan.",
    "这是什么牛啊? 西门塔尔，65块给你啦": "What kind of cattle is this? Simmental, I'll give it to you for 65 yuan.",
    "有吊龙吗": "Do you have Chuck Flap?",
    "多少钱": "How much?",
    "60": "60 yuan.",
    "那来半斤吧": "Then let's get half a catty.",
    "牛崭有吗": "Do you have beef shank?",
    "你要的话，低点给你": "If you want it, I'll give you a lower price.",
    "50块钱啊": "50 yuan.",
    "行 切半斤吧": "Okay, cut half a catty.",
    "25块，拿好了。": "25 yuan, here you go.",
    "那个50的吊龙给我来点吧": "Give me some of that 50 yuan Chuck Flap.",
    "最便宜的68": "The cheapest one is 68.",
    "啥？": "What?",
    "刚才他说50啊": "He just said 50 earlier.",
    "50的一般般，没有那么嫩滑": "The 50 yuan one is just average, not as tender and smooth.",
    "要半斤可以吗": "Is half a catty okay?",
    "可以可以": "Yes, sure.",
    "还要其它吗？": "Do you need anything else?",
    "五花子多少钱": "How much is the marbled shank (Wuhuazi)?",
    "最便宜的70": "The cheapest one is 70.",
    "切开全部是花的": "Once cut, you can see it's fully marbled.",
    "OK": "OK.",
    "有一个黄喉": "We have a piece of yellow throat (aorta).",
    "你要的话，70给你": "If you want it, I'll give it to you for 70.",
    "这一条70？": "This whole strip for 70?",
    "对": "Yes.",
    "再送一份牛红（牛血）给你吃": "I'll give you a free portion of beef blood to try.",
    "你等下7点半左右过来": "Come over around 7:30 later.",
    "还有那个会跳的牛肉（刚宰杀的牛肉）": "We'll have that twitching beef (freshly slaughtered).",
    "啊 好": "Ah, okay.",
    "一共买了275": "We bought 275 yuan worth in total.",
    "到对面加工，人家会帮你切好的。": "Go across the street for processing, they will slice it for you.",
    "我们找一家": "Let's find a place.",
    "来加工啦": "Coming for processing!",
    "就一个原则，找人多的吧": "Only one rule: look for the crowded ones.",
    "几位怎么吃？火锅还是烧烤": "How would you like to eat? Hotpot or BBQ?",
    "怎么收钱啊": "How do you charge?",
    "10块钱一个人": "10 yuan per person.",
    "还有一个炉子20块钱": "And 20 yuan for the stove.",
    "我们可以火锅加烧烤吗": "Can we do both hotpot and BBQ?",
    "我买半斤是70块": "I bought half a catty for 70 yuan.",
    "用不好的肉": "If they use bad meat...",
    "广东人做生意不会骗人的": "Guangdong people are honest in business.",
    "他还有调料": "He also has seasonings.",
    "这个是烤的 这个是煮的": "This one is for grilling, this one is for boiling.",
    "先拿好这些": "Hold these first.",
    "哦，可以合个影吗？": "Oh, can we take a photo together?",
    "安格斯的吊龙是75一斤": "Angus Chuck Flap is 75 yuan per catty.",
    "肉眼可见": "Visible to the naked eye.",
    "这里面吊龙最肥的": "The Chuck Flap is the fattiest part here.",
    "安格斯它的肉的最大的特点就是奶香": "The biggest feature of Angus beef is its milky flavor.",
    "这下午刚宰完两个小时的": "Freshly slaughtered just two hours ago this afternoon.",
    "其实不光是潮汕爱吃牛肉": "Actually, it's not just Chaoshan people who love beef.",
    "我觉得整个广东都争分夺秒": "I feel like the whole of Guangdong is racing against time for fresh beef.",
    "尝一下": "Let's have a taste.",
    "香": "Delicious!",
    "西门塔尔吊龙": "Simmental Chuck Flap.",
    "65一斤": "65 yuan per catty.",
    "虽然你看它瘦": "Although it looks lean.",
    "但是因为够新鲜": "But because it's fresh enough.",
    "吃起来是嫩的": "It tastes very tender.",
    "而且汁水很多": "And it's very juicy.",
    "其实广东这边吃西门塔尔比较多": "Actually, people in Guangdong eat Simmental more often.",
    "实惠 爽口": "Affordable and refreshing.",
    "这个吃多了不会腻": "You won't get tired of eating this.",
    "跟潮汕最大不同之处": "The biggest difference from Chaoshan style.",
    "它们讲究厚切": "They prefer thick cuts.",
    "我喜欢吃这个": "I love eating this.",
    "西门塔尔的牛崭": "Simmental beef shank.",
    "50一斤": "50 yuan per catty.",
    "它是小腿肉": "It's calf meat.",
    "紧实": "Firm and chewy.",
    "到点了": "It's time.",
    "跳的牛肉要出来了": "The twitching fresh beef is coming out.",
    "来半斤吧": "Let's get half a catty.",
    "可以拍个照吗？可以可以": "Can I take a photo? Yes, yes.",
    "就从宰到入口": "From slaughtering to taking a bite.",
    "可能就30分钟以内的": "Probably within 30 minutes.",
    "本地叫彩条": "Locals call it 'Caitiao'.",
    "其实就是嫩尖": "It's actually the tenderloin tip.",
    "这个更新鲜": "This is even fresher.",
    "基本上都是瘦的": "It's mostly lean meat.",
    "跟菲力很像": "Very similar to Filet Mignon.",
    "但区别在于它中间有条筋": "But the difference is there's a tendon in the middle.",
    "接下来我们涮一下": "Next, let's cook it in the hotpot.",
    "这是粥底啊": "This is a congee base hotpot.",
    "对 先把它放下去": "Yes, put it in first.",
    "吃粥一定要吃这个": "You must try this with congee.",
    "五花趾外面的筋": "The outer tendon of the marbled shank.",
    "让它多煲一会": "Let it simmer a bit longer.",
    "黄牛的五花趾": "Local cattle's marbled shank.",
    "70一斤": "70 yuan per catty.",
    "差不多30秒 好喽": "About 30 seconds, it's ready.",
    "老板切的可以": "The boss's slicing skills are excellent.",
    "这个五花趾还是比较讲究刀工的": "This marbled shank requires good knife skills.",
    "非常的爽 弹": "Very crisp and bouncy.",
    "最后我们尝尝最便宜的黄牛吊龙": "Finally, let's taste the cheapest local Chuck Flap.",
    "50一斤 我们买了39块钱": "50 per catty, we bought 39 yuan worth.",
    "这也太出肉了": "This yields so much meat.",
    "没问题啊": "No problem.",
    "我们能拍张照吗？": "Can we take a photo?",
    "可以可以可以": "Yes, sure!",
    "这油条哪买的": "Where did you buy these dough sticks?",
    "对面 就在对面": "Across the street, right opposite.",
    "靓仔，过来看一下": "Hey handsome, come and take a look.",
    "俩块钱一条": "2 yuan each.",
    "六根吧": "Six pieces then.",
    "最后做碗油条粥": "Finally, make a bowl of dough-stick congee.",
    "10块钱一个人的加工费": "10 yuan processing fee per person.",
    "那你怎么赚钱": "Then how do you make money?",
    "那小有小赚的嘛": "We make a small profit.",
    "饮料又挣一点": "We earn a bit from drinks too.",
    "进来是客人": "Everyone who comes in is a guest.",
    "你就有机会挣钱了": "Then you have a chance to make money.",
    "哎": "Hey.",
    "没想到佛山还有这样的地方": "I didn't expect Foshan to have a place like this.",
    "这挺宝藏": "This is quite a hidden gem.",
    "老板结账": "Boss, check please.",
    "88": "88 yuan.",
    "嗯": "Mm-hmm.",
    "还有饮料": "And drinks.",
    "99块": "99 yuan.",
    "99啦": "99 then.",
    "长长久久了": "Cheers to a long life!"
}

subs = pysrt.open(SRT_PATH, encoding='utf-8')

for sub in subs:
    lines = sub.text.split('\n')
    zh_text = lines[0].strip()
    
    if not zh_text:
        sub.text = "\n"
        continue
        
    # Get high-quality translation
    en_text = translations.get(zh_text)
    
    if not en_text:
        # Fallback only if absolutely necessary, but DO NOT modify Chinese
        en_text = zh_text
        
    sub.text = f"{zh_text}\n{en_text}"

subs.save(SRT_PATH, encoding='utf-8')
print("Complete LLM Translation Applied! Chinese was perfectly preserved.")
